#!/usr/bin/env bash

nick="$1"
mesg="$2"
ircd="$3"
netw="$4"
chan="$5"
self="$6"

read -r cmd extra <<< "$mesg"

#this is from the original iibot by c00kiemon5ter, not needed for now
#
#if [[ "$mesg" =~ .*\>.+ ]]; then
    #read -r nicks <<< "${extra#*>}"
    #read -r extra <<< "${extra%>*}"
#fi

#if [[ "$nicks" == "@all" ]]; then
    #printf -- "/names %s\n" "$chan"
    #nicks=""
    #while test -z "$nicks"; do # wait for the response
        #nicks="$(tail -n2 "$ircd/$netw/out" | grep "[[:digit:]-]\+ [[:digit:]:]\+ = $chan" | cut -d" " -f5-)"
        #sleep .5
    #done
#fi

commands=(
  help
  ping
  reversi
)

case "$cmd" in
  help)
    if [[ -n "$extra" ]]; then
      case "$extra" in
        reversi)
          echo "Usage: '!reversi start' to start the game"
          echo "       '!register' to enter the game"
          echo "          when two players registered for the game, it will start"
          echo "       '!reversi start1' to start the human vs AI game"
          echo "          the game will start immediately, human will be first"
          echo "       '!reversi start2' to start the human vs AI game"
          echo "          the game will start immediately, AI will be first"
          echo "       '!reversi stop' to stop the game"
          echo "Possible valid moves: '.a1', '.B2'"
          ;;
        ping)
          echo "Usage: '!ping' to test lag"
          ;;
        help)
          echo "Usage: '!help' to see the help"
          echo "       '!help COMMAND' to see the help about that COMMAND"
          echo "          available commands: ${commands[*]}"
          ;;
        *)
          echo "No help for $extra"
          ;;
      esac
    else
      echo "Usage: '!help COMMAND' to see the help about that COMMAND"
      echo "          available commands: ${commands[*]}"
    fi
    ;;
  ping) #just to test whether the bot is still alive or not
    printf -- "%s: pong!\n" "$nick"
    ;;
esac

